### ISSUE TITLE
Create a companies page

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs-docs#10]
[ ] Get approval for format of page
[ ] Design layout of page
[ ] Collect set of companies using RxJS
[ ] Create the ability for people to submit their company
[ ] Create the ability for approvals (is this just submitting a PR or should it be a form?
[ ] Finish creating the page!

**Comment by Only1MrAnderson** [comment]
@ladyleet I am looking at implementing this. Are you looking for some mockups before development work is started? Also, any thoughts on using firebase to store the list? Maybe overkill?

**Comment by ladyleet** [comment]
@only1mranderson  nothing has actually been started yet so yes maybe some mock up would be really good. I think initially we would like to just get companies on a page, however I think it would be really nice at some point in time for companies to be able to submit their logos and websites and have that list grow. Or maybe it's just a  Company list who knows. Open to ideas :-)

**Comment by Only1MrAnderson** [comment]
@ladyleet . I am thinking Material 2 table with Ngrx (good example of what Rxjs can do :) ) and hook that into firebase at the end. I will work on some mockups

**Comment by ladyleet** [comment]
Lovely!

**Comment by ladyleet** [comment]
@Only1MrAnderson @lordknighton a lot of companies are already listed on the rxworkshop.com page.

**Comment by Only1MrAnderson** [comment]
@ladyleet  thoughts? It is still missing validation, layout, and some style but seeing if this is even wanted before I put any work into it. 
![companies](https://user-images.githubusercontent.com/8826208/32138711-9132df0c-bc05-11e7-9fc4-4ada81bd6c23.gif)

**Comment by ladyleet** [comment]
@Only1MrAnderson I love this, but can we somehow add images/logos too? looks great! :)

**Comment by ladyleet** [comment]
@Only1MrAnderson also what are your thoughts for the backend? firebase?

**Comment by lordKnighton** [comment]
Ok so how about, once they submit their company to the company page: We should be able to use their logo from any source?

**Comment by ladyleet** [comment]
@lordKnighton most people are pretty particular about *which* logos are used is the problem.

**Comment by ladyleet** [comment]
@Only1MrAnderson maybe we should also have a checkbox saying "submitted on behalf of company" or "submitted by company" and then email address?

**Comment by Only1MrAnderson** [comment]
I was planning on adding the company logo on the left side where the building icon is showing now... This demo is already wired up to firebase.  I know the original requirement had them being approved. What is the thought with that? I have a few ideas to automate that just not sure of the reason behind approval. Is it just to prevent bots ? If so I could do github auth to submit ? Or I could possibly call a D&B service to validate company (need to see if we have all info)

I will submit an initial PR so that we can continue the communication as well as finish my goal for Hacktoberfest :)

**Comment by ladyleet** [comment]
I'm okay with no approval

**Comment by Airblader** [comment]
I'm not sure skipping approval would be a good idea. It seems like a footgun that invites people submitting all kinds of »funny« things (»rxjs used by Fart Corp.« and worse).

**Comment by Airblader** [comment]
Side note, why even go through the trouble of building a form to submit this which will probably be used quite rarely. Aren't Github PRs a perfect way of adding companies coming with a free approval process? :-)

**Comment by ladyleet** [comment]
i mean... @Airblader brings up fair points. :) i feel like skipping approval is also ok bc if it gets out of hand, we can change it.

**Comment by ashwin-sureshkumar** [comment]
Also, I agree with the point of just using PRs for adding companies. Thoughts ?

**Comment by Only1MrAnderson** [comment]
Could do OAuth with GitHub, that is baked into firebase

**Comment by Airblader** [comment]
Funnily I actually run a website that has a submission without approval process. The only reason I chose that is because it's too small, too specific and doesn't have any kind of free text to enter (but even there I at least send an email to myself for any submission). Personally I'd never choose that approach for something like this. Once some hate speech stuff shows up you might even have companies no longer wanting to be represented on that page because they don't want to be associated with it.

As an alternative to get a free approval process and still allow a form on the website, you could also do what I did on an older version of my website: use the form to automatically create a PR against the repository. Reviewing the PR and merging it acts as the approval in this case.

**Comment by Airblader** [comment]
(But for the record, I wouldn't expect this form to be used a whole lot anyway. In my opinion it'd be best to instead just have some kind of "Do you also use rxjs and want to be listed here? Send a PR or drop us an email" with appropriate links.)

**Comment by ladyleet** [comment]
@Airblader i dont like the email but the PR is great or maybe creating an issue with the specific items?

**Comment by Airblader** [comment]
I would assume that someone submitting a new company is typically tech-savy and not some executive or manager (who doesn't know what rxjs is), so I don't think having them submit a PR is asking too much. :-)

**Comment by ladyleet** [comment]
Agreed to!

**Comment by ashwin-sureshkumar** [comment]
PR incoming on top of @Only1MrAnderson to address the above discussion, since he is busy for a bit.

**Comment by btroncone** [comment]
@ladyleet @Airblader I agree, PR would be great. Having it completely open with no approval is too risky imo. 👍

**Comment by ashwin-sureshkumar** [comment]
@btroncone  PR is up.
